plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'com.aiden.dungeons.Main'
}

group = 'com.aiden.dungeons'
version = '0.0.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:1.14.0"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:1.14.0"
    implementation "com.badlogicgames.gdx:gdx-platform:1.14.0:natives-desktop"
}

distributions {
    main {
        distributionBaseName = 'aiden_dungeons'
    }
}